bot:
  name: "Lilly"
  messenger:
#    - 'discord'
    - 'telegram'
  description: ""
  environment:
    - name: "location"
      value: "Rahden"
    - name: "timezone"
      value: "Europe/Berlin"
    - name: "language"
      value: "de"
  plugins:
    - name: translate
    - name: wolfram
    - name: gas_prices
    - name: date
    - name: maps
    - name: entertainment
    - name: music
    - name: wiki
    - name: weather
    - name: welcome
    - name: movies
    - name: timer
    - name: help
    - name: nothing





