bot:
  name: "Lilly"
  description: ""
  environment:
    - name: "location"
      value: "Rahden"
    - name: "timezone"
      value: "Europe/Berlin"
  plugins:
    - name: wiki
    - name: weather
    - name: welcome




