plugin:
  name: "entertainment"
  description: "this is for entertainment, jokes, and so on

              nutzt:
                - lustige-sprueche.net"
  methods:
    - name: "user_is_boring"
      help: 'get some interesting infos, or jokes

            For example: __mir ist langweilig__'
      keywords:
        list:
          - "mir ist langweilig"
      answers:
        list:
          - "$response"
        params:
          - name: response
            description: "the response"
    - name: make_jokes
      help: 'get some jokes

            For example: __mach einen witz__'
      keywords:
        list:
          - 'mach einen witz'
          - 'erzähl mir einen witz'
          - 'kennst du einen witz'
      answers:
        list:
          - '$joke'
        params:
          - name: joke
            description: 'the joke'
