plugin:
  name: "movies"
  description: "You can get Infos about movies and actors"
  methods:
    - name: "get_movie_description"
      help: 'You get the description of a movie.

            Just ask for the content.

            For example: __wovon handelt the Matrix__'
      keywords:
        list:
          - "wovon handelt $movie"
          - "der inhalt von $movie"
        params:
          - name: movie
            count: 6
            description: "the movie"
      answers:
        list:
          - "Hier die Beschreibung:\n$description"
        params:
          - name: description
            description: "the result description"
    - name: "get_movie_cast"
      help: 'Get the first 7 actors a movie

            Ask: __wer spielt in the Matrix__'
      keywords:
        list:
          - "wer spielt in $movie"
        params:
          - name: movie
            count: 6
            description: "the movie"
      answers:
        list:
          - "Hier der Cast:\n$cast"
        params:
          - name: "cast"
            description: "the cast"

    - name: actor_details
      help: 'Get more Information about an actor.

            The question is: __filme von Morgan Freeman__'
      keywords:
        list:
          - "in welchen filme ist $actor"
          - "filme von $actor"
          - "$actor filme"
        params:
          - name: actor
            count: 4
            description: "the actor"
      answers:
        list:
          - "Hier die Details:$details"
        params:
          - name: details
            description: details of the actor

