plugin:
  name: "music"
  description: "eine Suchmaschine für songtexte und musiker"
  methods:
    - name: "get_album"
      help: ''
      keywords:
        list:
          - "alben von $singer"
        params:
          - name: "singer"
            count: 3
            description: "the singer of the album"
      answers:
        list:
          - "Hier sind die Alben:$result"
        params:
          - name: result
            description: "The result of the music search"
    - name: "get_lyric"
      help: ''
      keywords:
        list:
          - "text zu $song( von $singer)?"
        params:
          - name: "song"
            count: 5
            description: "the song"
          - name: "singer"
            count: 3
            description: "the singer of the album"
      answers:
        list:
          - "Der Text zu $song:$result"
        params:
          - name: song:
            description: "The name of the song"
          - name: result
            description: "The result of the music search"
