plugin:
  name: "music"
  description: description
  methods:
    - name: "get_album"
      help: get_album__help
      keywords:
        list:
          - get_album__albums
          - get_album__which
          - get_album__show
        params:
          - name: "singer"
            count: 3
            description: get_album__param_singer
      answers:
        list:
          - get_album__albums
        params:
          - name: result
            description: "The result of the music search"
    - name: "get_lyric"
      help: get_lyric__help
      keywords:
        list:
          - get_lyric__from
          - get_lyric__long_form
        params:
          - name: "song"
            count: 5
            description: get_lyric__param_song
          - name: "singer"
            count: 3
            description: get_lyric__param_singer
      answers:
        list:
          - get_lyric__lyrics
        params:
          - name: result
            description: "The result of the music search"
          - name: song
            description: "The name of the song"

