plugin:
  name: "nothing"
  description: description
  methods:
    - name: "wrong_command"
      keywords:
        list:
          - all
      answers:
        list:
          - wrong_command__wired
          - wrong_command__not_right
          - wrong_command__stop
          - wrong_command__what_to_do
          - wrong_command__confused

