plugin:
  name: "weather"
  description: "wetter station"
  methods:
    - name: "get_weather"
      help: 'Ask for the weather.

            Possible is:

            __wie ist das wetter__,

            __wie ist das wetter in Espelkamp__'
      keywords:
        list:
          - "gib mir das wetter( aus $standort)?( um $time)?"
          - "wie ist das wetter( in $standort)?( um $time)?"
        params:
          - name: standort
            default: ENV.standort
            type: string
            description: "the weather from where"
          - name: time
            type: string
            count: 2
            description: "from what date "
      answers:
        list:
          - "es ist $weather (in $standort)?( um $time)?"
          - "(um $time ist es )?$weather( in $standort)?"
        params:
          - name: weather
            description: ""
          - name: standort
            required: False
            description: "the weather from where"
          - name: time
            required: False
            description: "from what date or in how much minutes/hours"
