plugin:
  name: "weather"
  token: ""
  description: "wetter station"
  methods:
    - name: "get_weather"
      keywords:
        list:
          - "gib mir das wetter( aus $standort)?( um $time)?"
          - "wie ist das wetter( in $standort)?( um $time)?"
        params:
          - name: standort
            default: ENV.standort
            type: string
            description: "the weather from where"
          - name: time
            type: all
            count: 2
            description: "from what date "
      answers:
        list:
          - "es ist $weather (in $standort)?( um $time)?"
          - "(um $time ist es )?$weather( in $standort)?"
        params:
          - name: weather
            description:
          - name: standort
            description: "the weather from where"
          - name: time
            description: "from what date or in how much minutes/hours"
