plugin:
  name: "welcome"
  description: description
  methods:
    - name: "say_hello"
      help: say_hello__help
      keywords:
        list:
          - say_hello__hi
          - say_hello__hello
          - say_hello__moin
          - say_hello__evening
      answers:
        list:
          - say_hello__hi
          - say_hello__moin
          - say_hello__whats_up
          - say_hello__evening
          - say_hello__moin_moin
    - name: "how_are_you"
      help: how_are_you__help
      keywords:
        list:
          - how_are_you__how
          - how_are_you__whats_up
      answers:
        list:
          - how_are_you__fine
          - how_are_you__very_fine
    - name: "who_are_you"
      help: who_are_you__help
      keywords:
        list:
          - who_are_you__who
          - who_are_you__called
          - who_are_you__name
      answers:
        list:
          - who_are_you__i_am
          - who_are_you__name
          - who_are_you__hi
        params:
          - name: name
            description: who_are_you__param_name
    - name: "what_are_you_doing"
      help: what_are_you_doing__help
      keywords:
        list:
          - what_are_you_doing__what
      answers:
        list:
          - what_are_you_doing__doing
        params:
          - name: doing
            description: what_are_you_doing__param_doing
          - name: how
            description: what_are_you_doing__param_how
    - name: if_bot_needs_help
      help: if_bot_needs_help__help
      keywords:
        list:
          - if_bot_needs_help__how
          - if_bot_needs_help__possible
          - if_bot_needs_help__need
      answers:
        list:
          - if_bot_needs_help__no
          - if_bot_needs_help__health
          - if_bot_needs_help__nice
          - if_bot_needs_help__look
          - if_bot_needs_help__think
          - if_bot_needs_help__not_sure
    - name: how_old_is_bot
      help: how_old_is_bot__help
      keywords:
        list:
          - how_old_is_bot__old
          - how_old_is_bot__long
          - how_old_is_bot__exsist
          - how_old_is_bot__jears
      answers:
        list:
          - how_old_is_bot__i_am
          - how_old_is_bot__exist
          - how_old_is_bot__created
    - name: what_bot_is_able_to
      help: what_bot_is_able_to__help
      keywords:
        list:
          - what_bot_is_able_to__what
      answers:
        list:
          - what_bot_is_able_to__not_few
          - what_bot_is_able_to__learn
          - what_bot_is_able_to__skills
    - name: where_is_your_work
      help: where_is_your_work__help
      keywords:
        list:
          - where_is_your_work__where
          - where_is_your_work__description
          - where_is_your_work__what
      answers:
        list:
          - where_is_your_work__internet
          - where_is_your_work__homeoffice
          - where_is_your_work__customerservice
    - name: what_is_your_gender
      help: ''
      keywords:
        list:
          - what_is_your_gender__woman
          - what_is_your_gender__gender
          - what_is_your_gender__man
      answers:
        list:
          - what_is_your_gender__want
          - what_is_your_gender__role
          - what_is_your_gender__not_sure
          - what_is_your_gender__wired
          - what_is_your_gender__matter


