plugin:
  name: "welcome"
  description: "eine Suchmaschine"
  methods:
    - name: "say_hello"
      help: 'Just say hello or any greeting'
      keywords:
        list:
          - "hi\\b"
          - "hallo"
          - "moin"
          - "was geht"
          - "nabend"
      answers:
        list:
          - "Hi"
          - "Moin"
          - "Was geht"
          - "Nabend"
          - "Moin moin"
    - name: "how_are_you"
      help: 'How is the Bot.

            usage: __wie geht es dir__'
      keywords:
        list:
          - "wie geht(s)?( es dir)?"
          - "was geht"
      answers:
        list:
          - "Mir geht es sehr gut!"
          - "Mega gut"
    - name: "who_are_you"
      help: 'Asks for the name

            usage: __wer bist du__

            __wie ist dein name__'
      keywords:
        list:
          - "wer bist du"
          - "wie heißt du"
          - "wie ist dein name"
      answers:
        list:
          - "Ich bin $name"
          - "mein name ist $name"
          - "hi ich bin $name"
        params:
          - name: name
            desciption: "the name of the bot"
    - name: "what_are_you_doing"
      help: 'Ask what your bot is doing

            use: __was machst du__'
      keywords:
        list:
          - "was machst du( gerade)?"
      answers:
        list:
          - "$doing, $how"
        params:
          - name: doing
            description: "what am i doing"
          - name: how
            desciption: "how am i doing it"

