plugin:
  name: "welcome"
  token: ""
  description: "eine Suchmaschine"
  methods:
    - name: "say_hello"
      keywords:
        list:
          - "hi"
          - "hallo"
          - "moin"
          - "was geht"
          - "nabend"
          - "moin moin"
      answers:
        list:
          - "Hi"
          - "Moin"
          - "Was geht"
          - "Nabend"
          - "Moin moin"
    - name: "how_are_you"
      keywords:
        list:
          - "wie geht(s)?( es dir)?"
          - "was geht"
      answers:
        list:
          - "Mir geht es sehr gut!"
          - "Mega gut"
    - name: "who_are_you"
      keywords:
        list:
          - "wer bist du"
          - "wie heißt du"
          - "wie ist dein name"
      answers:
        list:
          - "Ich bin $name"
          - "mein name ist $name"
          - "hi ich bin $name"
        params:
          - name: name
            desciption: "the name of the bot"
    - name: "what_are_you_doing"
      keywords:
        list:
          - "was machst du( gerade)?"
      answers:
        list:
          - "$doing, $how"
        params:
          - name: doing
            description: "what am i doing"
          - name: how
            desciption: "how am i doing it"

