plugin:
  name: "wiki"
  description: description
  methods:
    - name: "search_wiki"
      help: search_wiki__help
      keywords:
        list:
          - search_wiki__who
          - search_wiki__what
        params:
          - name: "searchKeyword"
            count: 3
            description: search_wiki__param_searchKeyword
      answers:
        list:
          - search_wiki__result
        params:
          - name: result
            description: search_wiki__param_result
