plugin:
  name: "wiki"
  description: "eine Suchmaschine"
  methods:
    - name: "search_wiki"
      help: 'This will perform a  wiki search to get the summary

            ask __wer ist Taylor Swift__

            or __was ist ein Nomen__ => Thanks to my litle brother'
      keywords:
        list:
          - "wer ist( ein| eine| das| die| der)? $searchKeyword"
          - "was ist( ein| eine| das| die| der)? $searchKeyword"
        params:
          - name: "searchKeyword"
            count: 3
            description: "what to search for in wiki"
      answers:
        list:
          - "$result"
        params:
          - name: result
            description: "The result of the wiki search"
