plugin:
  name: "wiki"
  token: "bla"
  description: "eine Suchmaschine"
  methods:
    - name: "search_wiki"
      keywords:
        list:
          - "wer ist $searchKeyword"
          - "was ist $searchKeyword"
        params:
          - name: "searchKeyword"
            count: 3
            description: "what to search for in wiki"
      answers:
        list:
          - "$result"
        params:
          - name: result
            description: "The result of the wiki search"
