plugin:
  name: "wolfram"
  description: "a smart calculator"
  methods:
    - name: "add_numbers"
      help: 'Adds simply two numbers.

            ask __was ist 3 + 4__'
      keywords:
        list:
          - "was ist $first \\+ $second"
        params:
          - name: "first"
            count: 1
            type: number
            description: "the first number"
          - name: "second"
            count: 1
            type: number
            description: "the second number"
      answers:
        list:
          - "Das Ergebnis ist $result"
        params:
          - name: result
            description: "The result of the wiki search"
    - name: "calculate_term"
      help: 'Calculates more different math problems.

            use it like: __berechne 12 = x * 2__'
      keywords:
        list:
          - "berechne( mir)? $term"
        params:
          - name: "term"
            count: 8
            description: "the term that should be calculated"
      answers:
        list:
          - "Das Ergebnis ist $result"
        params:
          - name: result
            description: "the result of the term"
