bot: include('bot_type')
---
bot_type:
  name: str()
  messenger: list(str())
  description: str()
  environment: list(include('environment_type'))
  plugins: list(include('plugins_type'))

environment_type:
  name: str()
  value: str()

plugins_type:
  name: str()
